#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/bustersAgents.py /autograder/source/bustersAgents.py
cp /autograder/submission/inference.py /autograder/source/inference.py
cp /autograder/submission/factorOperations.py /autograder/source/factorOperations.py

cd /autograder/source

python3 autograder.py
